[dependencies]
deno = ">=2.8.3,<2.9"

[tasks]
export = "deno task export"

[workspace]
authors = ["Alexander Matsievsky <alexander.matsievsky@yandex.com>"]
channels = ["conda-forge"]
name = "resume"
platforms = ["linux-64"]
version = "3.0.0"
